### setXSRFCookie

GET http://localhost:8000/sanctum/csrf-cookie
Accept: application/json

### login

POST http://localhost:8000/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "secret"
}

###
